name: publish

on: [push]

jobs:

publish-hello-docker-image:

runs-on: ubuntu-latest

steps:

- uses: actions/checkout@v2

- name: Login to GitHub Container Registry

uses: docker/login-action@v1

with:

registry: ghcr.io

username: ${{ github.actor }}

password: ${{ secrets.GITHUB_TOKEN }}

- name: Build the production Docker image

run: |

       docker build  project/Dockerfile.prod -t ghcr.io/stephentyers1975/fastapi-tdd-docker/summarizer:latest

       docker run ghcr.io/stephentyers1975/fastapi-tdd-docker/summarizer:latest

       docker push ghcr.io/stephentyers1975/fastapi-tdd-docker/summarizer:latest